image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/


stages:          # List of stages for jobs, and their order of execution
  - setup
  - test
  - deploy

setup-job:       # This job runs in the build stage, which runs first.
  stage: setup
  script:
    - echo "Setting up virtual environment.."
    - python3 --version
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 --version
    - echo "Installing requirements.."
    - venv/bin/pip3 install -r requirements.txt

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo 'Running tests...'
    - venv/bin/python3 -m pytest

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "NOTIMPLEMENTED - Deploying application..."
    - echo "NOTIMPLEMENTED - Application successfully deployed."
