repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: detect-private-key
    - id: check-json
    - id: sort-simple-yaml
    - id: check-shebang-scripts-are-executable
    - id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.4'
    hooks:
    - id: bandit
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
