repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: flake8
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
